//Generated by GPT-4
let currentNumber, score = 0, round = 1;

function generateNumber() {
    return Math.floor(Math.random() * (10000 - 2 + 1)) + 2;
}

function getMaxPrimeFactor(n) {
    let maxPrime = -1;
    while (n % 2 === 0) {
        maxPrime = 2;
        n /= 2;
    }

    for (let i = 3; i <= Math.sqrt(n); i += 2) {
        while (n % i === 0) {
            maxPrime = i;
            n /= i;
        }
    }

    if (n > 2) maxPrime = n;

    return maxPrime;
}

function submitAnswer() {
    const playerAnswer = parseInt(document.getElementById('answer').value);
    const maxPrimeFactor = getMaxPrimeFactor(currentNumber);
    const digitPoints = currentNumber.toString().length * 10;
    const feedback = document.getElementById('feedback');
    const scoreDisplay = document.getElementById('score');

    if (playerAnswer === maxPrimeFactor) {
        score += digitPoints;
        feedback.innerText = 'Correct!';
    } else {
        score += 0; // ここで不正解時のロジックを追加することも可能
        feedback.innerText = `Incorrect! The correct answer was ${maxPrimeFactor}.`;
    }

    scoreDisplay.innerText = `Score: ${score}`;

    if (round < 10) {
        round++;
        nextRound();
    } else {
        feedback.innerText += ` Game Over! Final score: ${score}`;
    }
}

function nextRound() {
    currentNumber = generateNumber();
    document.getElementById('question').innerText = `Number: ${currentNumber}`;
    document.getElementById('answer').value = '';
}

document.addEventListener('DOMContentLoaded', (event) => {
    nextRound();
});